// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDazxsYOnr4QsqYbWMcKD-tXxWmYotfBmk',
    appId: '1:610102490806:web:7431d7320c228cb4acd817',
    messagingSenderId: '610102490806',
    projectId: 'aimeditationguide-d8e00',
    authDomain: 'aimeditationguide-d8e00.firebaseapp.com',
    storageBucket: 'aimeditationguide-d8e00.firebasestorage.app',
    measurementId: 'G-YRNKGHC5G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwVqSvYwK40MuN67jXWAkknHiyelZk1IY',
    appId: '1:610102490806:android:95e2bc7a47f4235eacd817',
    messagingSenderId: '610102490806',
    projectId: 'aimeditationguide-d8e00',
    storageBucket: 'aimeditationguide-d8e00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6LzQFYH0uW8zCBgXmcOPQqv3JkeeWGvU',
    appId: '1:610102490806:ios:effd552f8bb3125bacd817',
    messagingSenderId: '610102490806',
    projectId: 'aimeditationguide-d8e00',
    storageBucket: 'aimeditationguide-d8e00.firebasestorage.app',
    iosBundleId: 'com.example.aimeditationguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6LzQFYH0uW8zCBgXmcOPQqv3JkeeWGvU',
    appId: '1:610102490806:ios:effd552f8bb3125bacd817',
    messagingSenderId: '610102490806',
    projectId: 'aimeditationguide-d8e00',
    storageBucket: 'aimeditationguide-d8e00.firebasestorage.app',
    iosBundleId: 'com.example.aimeditationguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDazxsYOnr4QsqYbWMcKD-tXxWmYotfBmk',
    appId: '1:610102490806:web:a160b44c4d5cac21acd817',
    messagingSenderId: '610102490806',
    projectId: 'aimeditationguide-d8e00',
    authDomain: 'aimeditationguide-d8e00.firebaseapp.com',
    storageBucket: 'aimeditationguide-d8e00.firebasestorage.app',
    measurementId: 'G-JTZWSLB1RY',
  );
}
